// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourismBackend.DataContext;

#nullable disable

namespace TourismBackend.Migrations
{
    [DbContext(typeof(TourismContext))]
    [Migration("20240925222700_HomeProjectTour")]
    partial class HomeProjectTour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TourismServices.Models.pfActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItineraryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("pfActivities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ActivityName = "Visit the Eiffel Tower",
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9899),
                            Description = "Guided tour of the Eiffel Tower",
                            ItineraryID = 1
                        },
                        new
                        {
                            ID = 2,
                            ActivityName = "Boat ride on the Hudson",
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9902),
                            Description = "Cruise on the Hudson River",
                            ItineraryID = 2
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfAdministrator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("pfAdministrators");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "martin_fernandez@example.com",
                            LastName = "Fernandez",
                            Name = "Martin",
                            Phone = "3498479331",
                            RegistrationDate = new DateTime(2024, 9, 25, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9721)
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfClient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pfClients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Document = "123456789",
                            Email = "client1@example.com",
                            FirstName = "Client1",
                            LastName = "LastName1",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ID = 2,
                            Document = "987654321",
                            Email = "client2@example.com",
                            FirstName = "Client2",
                            LastName = "LastName2",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            ID = 3,
                            Document = "456789123",
                            Email = "client3@example.com",
                            FirstName = "Client3",
                            LastName = "LastName3",
                            PhoneNumber = "4567891230"
                        },
                        new
                        {
                            ID = 4,
                            Document = "321654987",
                            Email = "client4@example.com",
                            FirstName = "Client4",
                            LastName = "LastName4",
                            PhoneNumber = "3216549870"
                        },
                        new
                        {
                            ID = 5,
                            Document = "789123456",
                            Email = "client5@example.com",
                            FirstName = "Client5",
                            LastName = "LastName5",
                            PhoneNumber = "7891234560"
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfDestination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pfDestinations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Country = "France",
                            Description = "City of love",
                            Name = "Paris"
                        },
                        new
                        {
                            ID = 2,
                            Country = "United States",
                            Description = "The Big Apple",
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfExpense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExpenseCategory")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("pfExpenses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 100.00m,
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9965),
                            Description = "Hotel in Paris",
                            ExpenseCategory = 0,
                            ItineraryID = 1
                        },
                        new
                        {
                            ID = 2,
                            Amount = 50.00m,
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9968),
                            Description = "Food in New York",
                            ExpenseCategory = 1,
                            ItineraryID = 2
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfItinerary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("pfItineraries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartureDate = new DateTime(2024, 10, 2, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9993),
                            Description = "Trip to Paris",
                            Destination = "Paris",
                            ReturnDate = new DateTime(2024, 10, 9, 19, 26, 56, 103, DateTimeKind.Local).AddTicks(9998)
                        },
                        new
                        {
                            ID = 2,
                            DepartureDate = new DateTime(2024, 10, 16, 19, 26, 56, 104, DateTimeKind.Local),
                            Description = "Trip to New York",
                            Destination = "New York",
                            ReturnDate = new DateTime(2024, 10, 23, 19, 26, 56, 104, DateTimeKind.Local).AddTicks(1)
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfReservation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("ItineraryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("pfReservations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdministratorID = 0,
                            ClientID = 1,
                            ItineraryID = 1,
                            ReservationDate = new DateTime(2024, 9, 25, 19, 26, 56, 104, DateTimeKind.Local).AddTicks(31),
                            ReservationStatus = 0
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItineraryID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentConfirmation")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("pfTransactions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdministratorID = 0,
                            Amount = 1500.00m,
                            ClientID = 1,
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 104, DateTimeKind.Local).AddTicks(54),
                            ItineraryID = 1,
                            PaymentConfirmation = 1,
                            PaymentMethod = 1
                        },
                        new
                        {
                            ID = 2,
                            AdministratorID = 0,
                            Amount = 2000.00m,
                            ClientID = 2,
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 104, DateTimeKind.Local).AddTicks(141),
                            ItineraryID = 2,
                            PaymentConfirmation = 2,
                            PaymentMethod = 2
                        },
                        new
                        {
                            ID = 3,
                            AdministratorID = 0,
                            Amount = 500.00m,
                            ClientID = 3,
                            Date = new DateTime(2024, 9, 25, 19, 26, 56, 104, DateTimeKind.Local).AddTicks(144),
                            ItineraryID = 1,
                            PaymentConfirmation = 3,
                            PaymentMethod = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
