// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourismBackend.DataContext;

#nullable disable

namespace TourismBackend.Migrations
{
    [DbContext(typeof(TourismContext))]
    partial class TourismContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TourismServices.Models.pfActividad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItinerarioID")
                        .HasColumnType("int");

                    b.Property<string>("NombreActividad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pfActividades");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Tour guiado a la Torre Eiffel",
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8459),
                            ItinerarioID = 1,
                            NombreActividad = "Visita a la Torre Eiffel"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Crucero por el río Hudson",
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8461),
                            ItinerarioID = 2,
                            NombreActividad = "Paseo en barco por el Hudson"
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfAdministrador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pfAdministradores");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Fernandez",
                            Email = "martin_fernandez@example.com",
                            FechaRegistro = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8187),
                            Nombre = "Martin",
                            Telefono = "3498479331"
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfCliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pfClientes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Apellido = "Apellido1",
                            Documento = "123456789",
                            Email = "cliente1@example.com",
                            Nombre = "Cliente1",
                            Telefono = "1234567890"
                        },
                        new
                        {
                            ID = 2,
                            Apellido = "Apellido2",
                            Documento = "987654321",
                            Email = "cliente2@example.com",
                            Nombre = "Cliente2",
                            Telefono = "0987654321"
                        },
                        new
                        {
                            ID = 3,
                            Apellido = "Apellido3",
                            Documento = "456789123",
                            Email = "cliente3@example.com",
                            Nombre = "Cliente3",
                            Telefono = "4567891230"
                        },
                        new
                        {
                            ID = 4,
                            Apellido = "Apellido4",
                            Documento = "321654987",
                            Email = "cliente4@example.com",
                            Nombre = "Cliente4",
                            Telefono = "3216549870"
                        },
                        new
                        {
                            ID = 5,
                            Apellido = "Apellido5",
                            Documento = "789123456",
                            Email = "cliente5@example.com",
                            Nombre = "Cliente5",
                            Telefono = "7891234560"
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfDestino", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pfDestinos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Ciudad del amor",
                            Nombre = "París",
                            Pais = "Francia"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "La gran manzana",
                            Nombre = "Nueva York",
                            Pais = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfGasto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoriaGastoEnum")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItinerarioID")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID");

                    b.ToTable("pfGastos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoriaGastoEnum = 0,
                            Descripcion = "Hotel en París",
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8497),
                            ItinerarioID = 1,
                            Monto = 100.00m
                        },
                        new
                        {
                            ID = 2,
                            CategoriaGastoEnum = 1,
                            Descripcion = "Comida en Nueva York",
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8499),
                            ItinerarioID = 2,
                            Monto = 50.00m
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfItinerario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("pfItinerarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Viaje a París",
                            Destino = "París",
                            FechaRegreso = new DateTime(2024, 10, 9, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8533),
                            FechaSalida = new DateTime(2024, 10, 2, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8522)
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Viaje a Nueva York",
                            Destino = "Nueva York",
                            FechaRegreso = new DateTime(2024, 10, 23, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8536),
                            FechaSalida = new DateTime(2024, 10, 16, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8535)
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfReserva", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdministradorID")
                        .HasColumnType("int");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoReservaEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItinerarioID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("pfReservas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdministradorID = 0,
                            ClienteID = 1,
                            EstadoReservaEnum = 0,
                            FechaReserva = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8558),
                            ItinerarioID = 1
                        });
                });

            modelBuilder.Entity("TourismServices.Models.pfTransaccion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdministradorID")
                        .HasColumnType("int");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmacionPagoEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormaDePagoEnum")
                        .HasColumnType("int");

                    b.Property<int>("ItinerarioID")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID");

                    b.ToTable("pfTransacciones");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AdministradorID = 0,
                            ClienteID = 1,
                            ConfirmacionPagoEnum = 1,
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8581),
                            FormaDePagoEnum = 1,
                            ItinerarioID = 1,
                            Monto = 1500.00m
                        },
                        new
                        {
                            ID = 2,
                            AdministradorID = 0,
                            ClienteID = 2,
                            ConfirmacionPagoEnum = 2,
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8584),
                            FormaDePagoEnum = 2,
                            ItinerarioID = 2,
                            Monto = 2000.00m
                        },
                        new
                        {
                            ID = 3,
                            AdministradorID = 0,
                            ClienteID = 3,
                            ConfirmacionPagoEnum = 3,
                            Fecha = new DateTime(2024, 9, 25, 17, 20, 19, 378, DateTimeKind.Local).AddTicks(8586),
                            FormaDePagoEnum = 3,
                            ItinerarioID = 1,
                            Monto = 500.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
